/* ============================================================
   شحنك DZ — data.js
   بيانات الألعاب والتطبيقات والبطاقات واشتراكات ومحافظ الدفع الإلكتروني والأسئلة الشائعة
   الأسعار نموذجية — عدّلها حسب أسعار موردك الحقيقية
   ============================================================ */

/* ---------- الألعاب (شحن مباشر على معرف اللاعب) ---------- */
const GAMES = [
  {
    id: "pubg",
    name: "PUBG Mobile",
    alias: "ببجي شدات ببجي شدات يو سي يوسي",
    emoji: "🎯",
    sub: "شحن UC فوري",
    tags: ["الأكثر مبيعاً", "فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (Player ID) — تجده أسفل صورك الشخصية في اللعبة",
    packs: [
      { id: "uc60",   name: "60 UC",    sub: "باقة البداية",   price: 220,   bonus: null },
      { id: "uc325",  name: "325 UC",   sub: "+ مكافأة 25",    price: 950,   bonus: "بونص 25" },
      { id: "uc660",  name: "660 UC",   sub: "+ مكافأة 60",    price: 1800,  bonus: "بونص 60" },
      { id: "uc1800", name: "1800 UC",  sub: "+ مكافأة 180",   price: 4700,  bonus: "بونص 180" },
      { id: "uc3850", name: "3850 UC",  sub: "+ مكافأة 450",   price: 9500,  bonus: "بونص 450" },
      { id: "uc8100", name: "8100 UC",  sub: "باقة الملوك",    price: 19000, bonus: "بونص 1200" },
    ],
  },
  {
    id: "freefire",
    name: "Free Fire",
    alias: "فري فاير فريفاير جواهرات جواهر فاير",
    emoji: "🔥",
    sub: "جواهرات في ثوانٍ",
    tags: ["فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (ID) من صفحة الحساب في اللعبة",
    packs: [
      { id: "ff100",  name: "100 جوهرة",   sub: "باقة البداية",  price: 190,  bonus: null },
      { id: "ff310",  name: "310 جوهرة",   sub: "+ مكافأة 31",   price: 550,  bonus: "بونص 31" },
      { id: "ff520",  name: "520 جوهرة",   sub: "+ مكافأة 52",   price: 900,  bonus: "بونص 52" },
      { id: "ff1060", name: "1060 جوهرة",  sub: "+ مكافأة 106",  price: 1750, bonus: "بونص 106" },
      { id: "ff2180", name: "2180 جوهرة",  sub: "باقة المنافسة", price: 3500, bonus: "بونص 218" },
    ],
  },
  {
    id: "mobilelegends",
    name: "Mobile Legends",
    alias: "موبايل ليجندز ماس مبل",
    emoji: "⚔️",
    sub: "ماس ورموز سحرية",
    tags: ["جديد"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب ورقم المنطقة (Zone ID)",
    packs: [
      { id: "ml86",   name: "86 ماس",    sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "ml172",  name: "172 ماس",   sub: "+ مكافأة",      price: 470,  bonus: "بونص" },
      { id: "ml257",  name: "257 ماس",   sub: "+ مكافأة",      price: 700,  bonus: "بونص" },
      { id: "ml706",  name: "706 ماس",   sub: "باقة المتابعة", price: 1900, bonus: "بونص" },
      { id: "ml2195", name: "2195 ماس",  sub: "باقة الملوك",   price: 5600, bonus: "بونص" },
    ],
  },
  {
    id: "roblox",
    name: "Roblox",
    alias: "روبوكس روبلوكس",
    emoji: "🧱",
    sub: "روبوكس للحساب مباشرة",
    tags: ["الأكثر طلباً"],
    verifyType: "username",
    verifyHint: "أدخل اسم المستخدم (Username) الظاهر في حسابك",
    packs: [
      { id: "rbx80",   name: "80 روبوكس",   sub: "باقة البداية",  price: 260,   bonus: null },
      { id: "rbx400",  name: "400 روبوكس",  sub: "باقة البناء",   price: 1200,  bonus: null },
      { id: "rbx800",  name: "800 روبوكس",  sub: "باقة المبدعين", price: 2350,  bonus: null },
      { id: "rbx1700", name: "1700 روبوكس", sub: "باقة الاحتراف", price: 4800,  bonus: null },
      { id: "rbx4500", name: "4500 روبوكس", sub: "باقة الملوك",   price: 12500, bonus: null },
    ],
  },
  {
    id: "valorant",
    name: "Valorant",
    alias: "فالفورانت فالورانت فاليرانت نقاط",
    emoji: "🎮",
    sub: "نقاط VP لسلاحك المفضل",
    tags: ["شحن مباشر"],
    verifyType: "username",
    verifyHint: "أدخل اسم حساب Riot بصيغة name#tag — مثال: SniperDZ#EUW",
    packs: [
      { id: "vp1000", name: "1000 VP", sub: "باقة البداية",  price: 1350, bonus: null },
      { id: "vp2050", name: "2050 VP", sub: "+ مكافأة 250",  price: 2600, bonus: "بونص 250" },
      { id: "vp3650", name: "3650 VP", sub: "+ مكافأة 350",  price: 4600, bonus: "بونص 350" },
      { id: "vp5350", name: "5350 VP", sub: "باقة الاحتراف", price: 6700, bonus: null },
    ],
  },
  {
    id: "codm",
    name: "Call of Duty Mobile",
    alias: "كول اوف ديوتي كول أوف ديوتي كود موبايل",
    emoji: "🎖️",
    sub: "نقاط CP بالمعرّف مباشرة",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (UID) من إعدادات اللعبة ← معلومات الحساب",
    packs: [
      { id: "cp80",   name: "80 CP",    sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "cp420",  name: "420 CP",   sub: "+ مكافأة",      price: 1150, bonus: "بونص" },
      { id: "cp880",  name: "880 CP",   sub: "+ مكافأة",      price: 2300, bonus: "بونص" },
      { id: "cp2400", name: "2400 CP",  sub: "باقة الاحتراف", price: 6100, bonus: "بونص" },
    ],
  },
  {
    id: "genshin",
    name: "Genshin Impact",
    alias: "جنشن جينشن جينشين بلسورات",
    emoji: "🌠",
    sub: "بلورات جينيسِس + بركة القمر",
    tags: ["فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف HoYoverse (UID — 9 أرقام)",
    packs: [
      { id: "gs60",   name: "60 بلورة",     sub: "باقة البداية",         price: 260,   bonus: null },
      { id: "gs330",  name: "330 بلورة",    sub: "+ مكافأة 30",          price: 1300,  bonus: "بونص 30" },
      { id: "gs1090", name: "1090 بلورة",   sub: "+ مكافأة 90",          price: 4200,  bonus: "بونص 90" },
      { id: "gs2240", name: "2240 بلورة",   sub: "+ مكافأة 240",         price: 8400,  bonus: "بونص 240" },
      { id: "gs3880", name: "3880 بلورة",   sub: "باقة الملوك",          price: 14000, bonus: "بونص 600" },
      { id: "welkin", name: "بركة القمر",   sub: "اشتراك 30 يوماً يومياً", price: 900,  bonus: null },
    ],
  },
  {
    id: "clashofclans",
    name: "Clash of Clans",
    alias: "كلاش اوف كلانز كلاش",
    emoji: "🏰",
    sub: "جواهر لقريتك",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل وسم اللاعب (Player Tag) — يبدأ بـ # مثل #2ABC123",
    packs: [
      { id: "coc80",   name: "80 جوهرة",    sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "coc500",  name: "500 جوهرة",   sub: "+ مكافأة 65",   price: 1400, bonus: "بونص 65" },
      { id: "coc1200", name: "1200 جوهرة",  sub: "+ مكافأة 150",  price: 3300, bonus: "بونص 150" },
      { id: "coc2500", name: "2500 جوهرة",  sub: "باقة الاحتراف", price: 6500, bonus: "بونص 350" },
    ],
  },
  {
    id: "clashroyale",
    name: "Clash Royale",
    alias: "كلاش رويال",
    emoji: "👑",
    sub: "جواهر لكرسيك الملكي",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل وسم اللاعب (Player Tag) — يبدأ بـ # مثل #2ABC123",
    packs: [
      { id: "cr80",   name: "80 جوهرة",    sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "cr500",  name: "500 جوهرة",   sub: "+ مكافأة",      price: 1400, bonus: "بونص" },
      { id: "cr1200", name: "1200 جوهرة",  sub: "+ مكافأة",      price: 3300, bonus: "بونص" },
      { id: "cr2500", name: "2500 جوهرة",  sub: "باقة الاحتراف", price: 6500, bonus: "بونص" },
    ],
  },
  {
    id: "brawlstars",
    name: "Brawl Stars",
    alias: "براول ستارز برول ستارز",
    emoji: "⭐",
    sub: "جواهر لبطلك المفضل",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل وسم اللاعب (Player Tag) — يبدأ بـ # مثل #2ABC123",
    packs: [
      { id: "brs30",  name: "30 جوهرة",   sub: "باقة البداية",  price: 180,  bonus: null },
      { id: "brs80",  name: "80 جوهرة",   sub: "+ مكافأة",      price: 460,  bonus: "بونص" },
      { id: "brs170", name: "170 جوهرة",  sub: "+ مكافأة",      price: 900,  bonus: "بونص" },
      { id: "brs360", name: "360 جوهرة",  sub: "باقة الاحتراف", price: 1850, bonus: "بونص" },
    ],
  },
  {
    id: "8ballpool",
    name: "8 Ball Pool",
    alias: "بول ثمانية كرات 8 بول",
    emoji: "🎱",
    sub: "عملات لطاولتك",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (UID) من صفحة الحساب في اللعبة",
    packs: [
      { id: "8bp100",   name: "100 عملة",     sub: "باقة البداية",  price: 260,   bonus: null },
      { id: "8bp1000",  name: "1000 عملة",    sub: "+ مكافأة",      price: 2000,  bonus: "بونص" },
      { id: "8bp10000", name: "10 000 عملة",  sub: "باقة الاحتراف", price: 17000, bonus: "بونص" },
    ],
  },
  {
    id: "eafc",
    name: "EA FC موبايل",
    alias: "فيفا ايفا اي اف سي",
    emoji: "⚽",
    sub: "نقاط FC لفريق أحلامك",
    tags: ["جديد"],
    verifyType: "username",
    verifyHint: "أدخل معرّف EA (EA ID) الخاص بحسابك",
    packs: [
      { id: "fcp100",  name: "100 نقطة FC",  sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "fcp500",  name: "500 نقطة FC",  sub: "+ مكافأة",      price: 1150, bonus: "بونص" },
      { id: "fcp1200", name: "1200 نقطة FC", sub: "باقة الاحتراف", price: 2700, bonus: "بونص" },
    ],
  },
  {
    id: "fortnite",
    name: "Fortnite",
    alias: "فورتنايت فورتيناب فورت نايت",
    emoji: "🛠️",
    sub: "V-Bucks للمعركة الملكية",
    tags: ["جديد"],
    verifyType: "username",
    verifyHint: "أدخل اسم حساب Epic Games",
    packs: [
      { id: "vb1000",  name: "1000 V-Bucks",  sub: "باقة المعركة",  price: 1700,  bonus: null },
      { id: "vb2800",  name: "2800 V-Bucks",  sub: "باقة التواقم",  price: 4600,  bonus: null },
      { id: "vb5000",  name: "5000 V-Bucks",  sub: "باقة الأساطير", price: 7900,  bonus: null },
      { id: "vb13500", name: "13500 V-Bucks", sub: "باقة الملوك",   price: 19000, bonus: null },
    ],
  },
  {
    id: "steam",
    name: "بطاقة Steam Wallet",
    alias: "ستيم ستيام محفظة",
    emoji: "🕹️",
    sub: "رصيد متجر عالمي",
    tags: ["رمز يوصلك على البريد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "st10", name: "بطاقة 10$",  sub: "رمز رقمي فوري", price: 2200,  bonus: null },
      { id: "st20", name: "بطاقة 20$",  sub: "رمز رقمي فوري", price: 4300,  bonus: null },
      { id: "st50", name: "بطاقة 50$",  sub: "رمز رقمي فوري", price: 10500, bonus: null },
    ],
  },
  {
    id: "ludo",
    name: "Ludo Master / Ludo Star",
    alias: "لودو لودو ستار",
    emoji: "🎲",
    sub: "ألماس وذهب للعبة اللودو",
    tags: ["كلاسيكية"],
    verifyType: "username",
    verifyHint: "أدخل اسم حسابك في اللعبة كما هو مكتوب",
    packs: [
      { id: "ld1", name: "ألماس 500",     sub: "حزمة البداية",   price: 350,  bonus: null },
      { id: "ld2", name: "ألماس 1200",    sub: "+ مكافأة",       price: 750,  bonus: "بونص" },
      { id: "ld3", name: "ألماس 5000",    sub: "باقة المنافسة",  price: 2800, bonus: "بونص" },
    ],
  },
  {
    id: "carrom",
    name: "Carrom Pool",
    alias: "كاروم كاروم بول",
    emoji: "🎯",
    sub: "عملات ذهبية للكاروم",
    tags: ["كلاسيكية"],
    verifyType: "username",
    verifyHint: "أدخل اسم حسابك في اللعبة كما هو مكتوب",
    packs: [
      { id: "cp1", name: "100 عملة",   sub: "حزمة البداية", price: 300,  bonus: null },
      { id: "cp2", name: "500 عملة",   sub: "+ مكافأة",     price: 1200, bonus: "بونص" },
      { id: "cp3", name: "2000 عملة",  sub: "باقة الملوك",  price: 4200, bonus: "بونص" },
    ],
  },
  {
    id: "higgsdomino",
    name: "Higgs Domino",
    alias: "هيغز دومينو دومينو شيب هيجز",
    emoji: "🁢",
    sub: "شحن رقائق Domino Global",
    tags: ["الأكثر طلبًا"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (ID) من صفحة الملف الشخصي",
    packs: [
      { id: "hd300",  name: "300 مليون رقاقة",   sub: "حزمة البداية",  price: 900,   bonus: null },
      { id: "hd700",  name: "700 مليون رقاقة",   sub: "+ مكافأة",      price: 1900,  bonus: "بونص" },
      { id: "hd1750", name: "1.75 مليار رقاقة",  sub: "باقة المنافسة", price: 4500,  bonus: "بونص" },
      { id: "hd4250", name: "4.25 مليار رقاقة",  sub: "باقة الملوك",   price: 10500, bonus: "بونص" },
    ],
  },
  {
    id: "yalla",
    name: "Yalla Ludo",
    alias: "يلا لودو يلا",
    emoji: "🃏",
    sub: "ماسات Yalla Ludo",
    tags: ["الأكثر طلبًا"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (ID) من إعدادات اللعبة",
    packs: [
      { id: "yl60",   name: "60 ماسة",    sub: "حزمة البداية",  price: 380,  bonus: null },
      { id: "yl310",  name: "310 ماسة",   sub: "+ مكافأة",      price: 1750, bonus: "بونص" },
      { id: "yl1080", name: "1080 ماسة",  sub: "باقة المنافسة", price: 5400, bonus: "بونص" },
    ],
  },
  {
    id: "sussy",
    name: "Suspects Mystery",
    alias: "سوسي سوسي بوي",
    emoji: "🕵️",
    sub: "جواهر Mystery Mansion",
    tags: ["جديد"],
    verifyType: "username",
    verifyHint: "أدخل اسم المستخدم الظاهر في حسابك",
    packs: [
      { id: "sm1", name: "80 جوهرة",   sub: "حزمة البداية", price: 450,  bonus: null },
      { id: "sm2", name: "500 جوهرة",  sub: "+ مكافأة",     price: 2400, bonus: "بونص" },
    ],
  },
  {
    id: "onepiece",
    name: "One Piece Fighting",
    alias: "ون بيس ون بيس لوت",
    emoji: "🏴‍☠️",
    sub: "ماسات One Piece Mobile",
    tags: ["أنمي"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (ID) من صفحة الحساب",
    packs: [
      { id: "op1", name: "60 ماسة",    sub: "حزمة البداية", price: 600,  bonus: null },
      { id: "op2", name: "320 ماسة",   sub: "+ مكافأة",     price: 2900, bonus: "بونص" },
      { id: "op3", name: "980 ماسة",   sub: "باقة الملوك",  price: 8200, bonus: "بونص" },
    ],
  },
  {
    id: "bloodstrike",
    name: "Blood Strike",
    alias: "بلود سترايك بلودستريك",
    emoji: "🩸",
    sub: "شحن رصيد Blood Strike",
    tags: ["جديد", "فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (ID) من صفحة الملف الشخصي",
    packs: [
      { id: "bs100",  name: "100 Gold",   sub: "حزمة البداية",  price: 480,  bonus: null },
      { id: "bs570",  name: "570 Gold",   sub: "+ مكافأة",      price: 2300, bonus: "بونص" },
      { id: "bs1180", name: "1180 Gold",  sub: "باقة المنافسة", price: 4500, bonus: "بونص" },
    ],
  },
  {
    id: "efootball",
    name: "eFootball 2026",
    alias: "اي فوتبول ايفو فوتبول بيس",
    emoji: "⚽",
    sub: "عملات eFootball",
    tags: ["فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب من صفحة الحساب في اللعبة",
    packs: [
      { id: "ef100",  name: "100 عملة",  sub: "حزمة البداية",  price: 550,  bonus: null },
      { id: "ef550",  name: "550 عملة",  sub: "+ مكافأة",      price: 2600, bonus: "بونص" },
      { id: "ef1300", name: "1300 عملة", sub: "باقة المنافسة", price: 5900, bonus: "بونص" },
    ],
  },
  {
    id: "naraka",
    name: "Naraka Mobile",
    alias: "ناراكا ناراكا بلادبوينت",
    emoji: "🏹",
    sub: "عملات Naraka",
    tags: ["جديد"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب من إعدادات اللعبة",
    packs: [
      { id: "nk60",  name: "60 Jade",   sub: "حزمة البداية", price: 420,  bonus: null },
      { id: "nk300", name: "300 Jade",  sub: "+ مكافأة",     price: 1900, bonus: "بونص" },
    ],
  },
  {
    id: "supersus",
    name: "Super Sus",
    alias: "سوبر سوس ايمو سوس",
    emoji: "🚀",
    sub: "جواهر Super Sus",
    tags: ["جديد"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب من صفحة الحساب",
    packs: [
      { id: "ss1", name: "80 جوهرة",  sub: "حزمة البداية", price: 400,  bonus: null },
      { id: "ss2", name: "420 جوهرة", sub: "+ مكافأة",     price: 1900, bonus: "بونص" },
    ],
  },
  {
    id: "lodu",
    name: "Ludo Party",
    alias: "لودو لودو النجم",
    emoji: "🎪",
    sub: "شحن Ludo Party",
    tags: ["كلاسيكية"],
    verifyType: "username",
    verifyHint: "أدخل اسم المستخدم الظاهر في حسابك",
    packs: [
      { id: "lp1", name: "ألماس 300",  sub: "حزمة البداية", price: 320, bonus: null },
      { id: "lp2", name: "ألماس 900",  sub: "+ مكافأة",     price: 850, bonus: "بونص" },
    ],
  },
  {
    id: "archero",
    name: "Archero / Survivor",
    alias: "ارشيرو ارشيرو 3",
    emoji: "🎯",
    sub: "جواهر Archero io",
    tags: ["أكشن"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب من صفحة الحساب",
    packs: [
      { id: "ar1", name: "60 جوهرة",  sub: "حزمة البداية", price: 400, bonus: null },
      { id: "ar2", name: "300 جوهرة", sub: "+ مكافأة",     price: 1800, bonus: "بونص" },
    ],
  },
  {
    id: "stumbleguys",
    name: "Stumble Guys",
    alias: "ستامبل جايز ستامبل",
    emoji: "🎈",
    sub: "جواهر Stumble Guys",
    tags: ["الأكثر طلبًا", "فوري"],
    verifyType: "username",
    verifyHint: "أدخل اسم المستخدم الظاهر في حسابك",
    packs: [
      { id: "sg1", name: "150 جوهرة",  sub: "حزمة البداية",  price: 380,  bonus: null },
      { id: "sg2", name: "750 جوهرة",  sub: "+ مكافأة",      price: 1700, bonus: "بونص" },
      { id: "sg3", name: "1700 جوهرة", sub: "باقة المنافسة", price: 3700, bonus: "بونص" },
    ],
  },
  {
    id: "riseofkingdoms",
    name: "Rise of Kingdoms",
    alias: "رايز اوف كينجدومز رايز",
    emoji: "🏛️",
    sub: "جواهر Rise of Kingdoms",
    tags: ["استراتيجية"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب من صفحة الحساب",
    packs: [
      { id: "rok1", name: "880 جوهرة",   sub: "حزمة البداية",  price: 400,  bonus: null },
      { id: "rok2", name: "4400 جوهرة",  sub: "+ مكافأة",      price: 1850, bonus: "بونص" },
      { id: "rok3", name: "10900 جوهرة", sub: "باقة المنافسة", price: 4400, bonus: "بونص" },
    ],
  },
  {
    id: "lordsmobile",
    name: "Lords Mobile",
    alias: "لوردز موبايل لوردز",
    emoji: "🏰",
    sub: "جواهر Lords Mobile",
    tags: ["استراتيجية"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب من صفحة الحساب",
    packs: [
      { id: "lm1", name: "390 جوهرة",  sub: "حزمة البداية",  price: 380,  bonus: null },
      { id: "lm2", name: "1990 جوهرة", sub: "+ مكافأة",      price: 1750, bonus: "بونص" },
      { id: "lm3", name: "5390 جوهرة", sub: "باقة المنافسة", price: 4500, bonus: "بونص" },
    ],
  },
  {
    id: "stateofsurvival",
    name: "State of Survival",
    alias: "ستيت اوف سرفيفل ستيت",
    emoji: "🧟",
    sub: "بيتكوينات وأموال SOS",
    tags: ["استراتيجية"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب من صفحة الحساب",
    packs: [
      { id: "sos1", name: "بيتكوين 1000",  sub: "حزمة البداية",  price: 420,  bonus: null },
      { id: "sos2", name: "بيتكوين 5500",  sub: "+ مكافأة",      price: 2100, bonus: "بونص" },
      { id: "sos3", name: "بيتكوين 13500", sub: "باقة المنافسة", price: 4800, bonus: "بونص" },
    ],
  },
];

/* ---------- بطاقات واشتراكات (تسليم على البريد) ---------- */
const CARDS = [
  {
    id: "netflix",
    name: "Netflix",
    alias: "نتفلكس نتفليكس نيتفلكس",
    emoji: "🎬",
    sub: "أفلام ومسلسلات بجودة 4K",
    tags: ["الأكثر طلباً", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "nf1", name: "شهر واحد", sub: "باقة البداية · جودة 4K", price: 1500, bonus: null },
      { id: "nf2", name: "شهرين",   sub: "جودة 4K · شاشتان",      price: 2800, bonus: "توفير 200" },
      { id: "nf3", name: "3 أشهر",  sub: "جودة 4K · شاشتان",      price: 4000, bonus: "توفير 500" },
    ],
  },
  {
    id: "shahid",
    name: "شاهد VIP",
    alias: "شاهد شاهد في اي بي شاهد في اي بي",
    emoji: "📺",
    sub: "أفلام ومسلسلات عربية وأجنبية",
    tags: ["عربي", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "sh1",  name: "شهر واحد VIP",  sub: "باقة البداية",     price: 900,  bonus: null },
      { id: "sh3",  name: "3 أشهر VIP",    sub: "باقة العائلة",     price: 2500, bonus: "بونص" },
      { id: "sh12", name: "سنة كاملة VIP", sub: "أفضل قيمة",        price: 8500, bonus: "توفير كبير" },
    ],
  },
  {
    id: "spotify",
    name: "Spotify Premium",
    alias: "سبوتيفاي سبوتيفايا سبوتيفاي بريميوم",
    emoji: "🎵",
    sub: "موسيقى بلا إعلانات",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "sp1",  name: "شهر واحد", sub: "حساب فردي",   price: 900,  bonus: null },
      { id: "sp3",  name: "3 أشهر",   sub: "حساب فردي",   price: 2500, bonus: "توفير" },
      { id: "sp6",  name: "6 أشهر",   sub: "حساب فردي",   price: 4700, bonus: "توفير أكبر" },
      { id: "sp12", name: "12 شهراً", sub: "أفضل قيمة",   price: 8500, bonus: "أفضل قيمة" },
    ],
  },
  {
    id: "youtube",
    name: "YouTube Premium",
    alias: "يوتيوب يوتيوب بريميوم يوتيوب برييم",
    emoji: "▶️",
    sub: "بلا إعلانات + يوتيوب موسيقى",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "yt1",  name: "شهر واحد",  sub: "حساب فردي", price: 950,  bonus: null },
      { id: "yt3",  name: "3 أشهر",    sub: "حساب فردي", price: 2700, bonus: "توفير" },
      { id: "yt12", name: "سنة كاملة", sub: "أفضل قيمة", price: 9900, bonus: "توفير كبير" },
    ],
  },
  {
    id: "discord",
    name: "Discord Nitro",
    alias: "ديسكورد ديسكورد نيترو نيترو",
    emoji: "🚀",
    sub: "إيموجي عالمي + بث HD",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز Nitro عليه",
    packs: [
      { id: "dn1", name: "شهر Nitro كامل", sub: "ترقية كاملة",     price: 1700, bonus: null },
      { id: "dn2", name: "14 يوم Boost",   sub: "تعبئة سيرفر",     price: 950,  bonus: null },
    ],
  },
  {
    id: "anghami",
    name: "أنغامي",
    alias: "انغامي انغامي بلس انغامي",
    emoji: "🎧",
    sub: "موسيقى عربية بلا إعلانات",
    tags: ["عربي", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "ang3",  name: "3 أشهر",   sub: "حساب فردي", price: 1600, bonus: null },
      { id: "ang12", name: "سنة كاملة", sub: "أفضل قيمة", price: 5200, bonus: "توفير" },
    ],
  },
  {
    id: "googleplay",
    name: "Google Play",
    alias: "جوجل بلاي بلاي ستور جوجل بلاي",
    emoji: "🤖",
    sub: "رصيد متجر أندرويد",
    tags: ["رمز يوصلك على البريد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "gp5",  name: "بطاقة 5$",  sub: "رمز رقمي فوري", price: 1150, bonus: null },
      { id: "gp10", name: "بطاقة 10$", sub: "رمز رقمي فوري", price: 2200, bonus: null },
      { id: "gp25", name: "بطاقة 25$", sub: "رمز رقمي فوري", price: 5400, bonus: null },
    ],
  },
  {
    id: "itunes",
    name: "iTunes / App Store",
    alias: "ايتونز آيتونز ابل ابل بطاقة",
    emoji: "🍎",
    sub: "رصيد متجر آبل",
    tags: ["رمز يوصلك على البريد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "it5",  name: "بطاقة 5$",  sub: "رمز رقمي فوري", price: 1150,  bonus: null },
      { id: "it10", name: "بطاقة 10$", sub: "رمز رقمي فوري", price: 2200,  bonus: null },
      { id: "it20", name: "بطاقة 20$", sub: "رمز رقمي فوري", price: 4300,  bonus: null },
      { id: "it50", name: "بطاقة 50$", sub: "رمز رقمي فوري", price: 10500, bonus: null },
    ],
  },
  {
    id: "razer",
    name: "Razer Gold",
    alias: "رايزر ريزر ريزر جولد",
    emoji: "🐍",
    sub: "رصيد ألعاب عالمي",
    tags: ["رمز يوصلك على البريد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "rz5",   name: "بطاقة 5$",   sub: "رمز رقمي فوري", price: 1150,  bonus: null },
      { id: "rz10",  name: "بطاقة 10$",  sub: "رمز رقمي فوري", price: 2200,  bonus: null },
      { id: "rz20",  name: "بطاقة 20$",  sub: "رمز رقمي فوري", price: 4400,  bonus: null },
      { id: "rz50",  name: "بطاقة 50$",  sub: "رمز رقمي فوري", price: 11000, bonus: null },
      { id: "rz100", name: "بطاقة 100$", sub: "رمز رقمي فوري", price: 21500, bonus: null },
    ],
  },
  {
    id: "xbox",
    name: "Xbox Game Pass",
    alias: "اكس بوكس اكس بوكس جيم باس",
    emoji: "🕹️",
    sub: "مئات الألعاب شهرياً",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "xgp1", name: "شهر واحد",  sub: "Game Pass Ultimate", price: 4500,  bonus: null },
      { id: "xgp3", name: "3 أشهر",    sub: "Ultimate",          price: 12500, bonus: "توفير" },
    ],
  },
  {
    id: "psplus",
    name: "PlayStation Plus",
    alias: "بلايستيشن بلايستيشن بلس بلاستيشن",
    emoji: "🎮",
    sub: "ألعاب PS5 و PS4 شهرياً",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "psp1",  name: "شهر واحد",  sub: "Essential", price: 3400,  bonus: null },
      { id: "psp3",  name: "3 أشهر",    sub: "Essential", price: 9500,  bonus: "توفير" },
      { id: "psp12", name: "12 شهراً",  sub: "Essential", price: 30000, bonus: "أفضل قيمة" },
    ],
  },
  {
    id: "osn",
    name: "OSN Streaming",
    alias: "او اس ان او اس ان",
    emoji: "🎬",
    sub: "أفلام HBO ومسلسلات عالمية",
    tags: ["جديد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "osn1",  name: "شهر واحد",  sub: "باقة البداية", price: 1900,  bonus: null },
      { id: "osn3",  name: "3 أشهر",    sub: "باقة العائلة", price: 5200,  bonus: "توفير" },
      { id: "osn12", name: "12 شهرًا",  sub: "أفضل قيمة",    price: 18000, bonus: "توفير كبير" },
    ],
  },
  {
    id: "watcho",
    name: "Watcho",
    alias: "واتشو واتش او",
    emoji: "📺",
    sub: "رياضة ومحتوى مباشر",
    tags: ["جديد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "wo1", name: "شهر واحد",  sub: "باقة البداية", price: 700,  bonus: null },
      { id: "wo6", name: "6 أشهر",    sub: "توفير",        price: 3600, bonus: "توفير" },
    ],
  },
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    alias: "كرانشي رول كرانشي رول",
    emoji: "🍥",
    sub: "أنمي بترجمة احترافية",
    tags: ["أنمي"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "cr1",  name: "شهر Fan",     sub: "باقة البداية",  price: 700,  bonus: null },
      { id: "cr3",  name: "3 أشهر Mega", sub: "شاشات متعددة",  price: 2400, bonus: "بونص" },
      { id: "cr12", name: "سنة Mega",    sub: "أفضل قيمة",     price: 8500, bonus: "توفير كبير" },
    ],
  },
  {
    id: "starzplay",
    name: "STARZPLAY",
    alias: "ستارزبلاي ستارز بلاي ستارزبلاي",
    emoji: "⭐",
    sub: "أفلام ومسلسلات حصرية",
    tags: ["جديد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "sz1", name: "شهر واحد",  sub: "باقة البداية", price: 800,  bonus: null },
      { id: "sz3", name: "3 أشهر",    sub: "توفير",        price: 2200, bonus: "توفير" },
    ],
  },
  {
    id: "shahidweek",
    name: "شاهد VIP أسبوعي",
    alias: "شاهد اسبوعي شاهد اسبوع",
    emoji: "🎁",
    sub: "تجربة VIP بأسبوع",
    tags: ["عربي"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "shw1", name: "أسبوع VIP",   sub: "تجربة سريعة",   price: 300,  bonus: null },
      { id: "shw4", name: "4 أسابيع VIP", sub: "شهر كامل VIP", price: 900,  bonus: "توفير" },
    ],
  },
  {
    id: "paramount",
    name: "Paramount+",
    alias: "باراماونت باراماونت بلس",
    emoji: "🏔️",
    sub: "أفلام ومسلسلات باراماونت",
    tags: ["جديد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "pm1",  name: "شهر واحد",  sub: "باقة البداية", price: 850,  bonus: null },
      { id: "pm12", name: "12 شهرًا",  sub: "أفضل قيمة",    price: 8500, bonus: "توفير كبير" },
    ],
  },
  {
    id: "layalina",
    name: "ليالينا (Abu Dhabi TV)",
    alias: "ليالينا ليالينا",
    emoji: "🏜️",
    sub: "باقات الأفلام العربية",
    tags: ["عربي"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "ly1",  name: "شهر واحد",  sub: "باقة البداية", price: 500,  bonus: null },
      { id: "ly12", name: "12 شهرًا",  sub: "أفضل قيمة",    price: 4500, bonus: "توفير كبير" },
    ],
  },
  {
    id: "noon",
    name: "بطاقات noon الشرائية",
    alias: "نون نون",
    emoji: "🛍️",
    sub: "رمز خصم/شراء لمتجر noon",
    tags: ["تسوق", "فوري"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "no25",  name: "بطاقة 25 درهم",  sub: "رمز فوري", price: 900,   bonus: null },
      { id: "no50",  name: "بطاقة 50 درهم",  sub: "رمز فوري", price: 1750,  bonus: null },
      { id: "no100", name: "بطاقة 100 درهم", sub: "رمز فوري", price: 3450,  bonus: null },
    ],
  },
  {
    id: "tamatem",
    name: "بطاقات Tamatem",
    alias: "تاماتم تاماتم كوينز",
    emoji: "💎",
    sub: "بطاقات تمتم للشحن",
    tags: ["فوري"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "tt10", name: "بطاقة 10$ (تمتم)", sub: "رمز فوري", price: 2350,  bonus: null },
      { id: "tt25", name: "بطاقة 25$ (تمتم)", sub: "رمز فوري", price: 5700,  bonus: null },
    ],
  },
  {
    id: "codashop",
    name: "بطاقات Codashop",
    alias: "كوداشوب كودا شوب",
    emoji: "🧾",
    sub: "بطاقات شحن فورية",
    tags: ["فوري"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "cd5",  name: "بطاقة 5$ (Coda)",  sub: "رمز فوري", price: 1250,  bonus: null },
      { id: "cd10", name: "بطاقة 10$ (Coda)", sub: "رمز فوري", price: 2400,  bonus: null },
    ],
  },
  {
    id: "pubgcode",
    name: "رمز UC مباشر",
    alias: "كود ببجي شدة ببجي كود",
    emoji: "🎫",
    sub: "رمز UC تشحنه بنفسك",
    tags: ["فوري"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز UC عليه",
    packs: [
      { id: "puc60",  name: "رمز 60 UC",   sub: "رمز فوري", price: 230,  bonus: null },
      { id: "puc325", name: "رمز 325 UC",  sub: "رمز فوري", price: 990,  bonus: null },
      { id: "puc660", name: "رمز 660 UC",  sub: "رمز فوري", price: 1900, bonus: null },
    ],
  },
  {
    id: "canva",
    name: "Canva Pro",
    alias: "كانفا كانفا برو",
    emoji: "🖌️",
    sub: "تصميم احترافي بلا حدود",
    tags: ["جديد", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "cv1",  name: "شهر واحد",  sub: "Pro · فردي",   price: 1200,  bonus: null },
      { id: "cv12", name: "12 شهرًا",  sub: "Pro · سنوي",   price: 11000, bonus: "توفير كبير" },
    ],
  },
];

/* ---------- تطبيقات ومواقع (شحن مباشر على الحساب) ---------- */
const APPS = [
  {
    id: "tiktok",
    name: "TikTok Coins",
    alias: "تيك توك تيك توك كوينز تكتوك",
    emoji: "🎵",
    sub: "شحن عملات تيك توك للبث",
    tags: ["الأكثر طلبًا", "فوري"],
    verifyType: "username",
    verifyHint: "أدخل اسم مستخدم تيك توك (@username) بدون مسافات",
    packs: [
      { id: "ttk70",   name: "70 عملة",    sub: "لإهداء وردة",    price: 260,   bonus: null },
      { id: "ttk350",  name: "350 عملة",   sub: "لإهداء هدية",    price: 1200,  bonus: null },
      { id: "ttk700",  name: "700 عملة",   sub: "لإهداء أسد",     price: 2350,  bonus: "بونص" },
      { id: "ttk1400", name: "1400 عملة",  sub: "باقة المبدعين",  price: 4600,  bonus: "بونص" },
      { id: "ttk3500", name: "3500 عملة",  sub: "باقة المشاهير",  price: 11000, bonus: "بونص" },
    ],
  },
  {
    id: "bigo",
    name: "BIGO LIVE",
    alias: "بيغو لايف بيغو",
    emoji: "🔴",
    sub: "شحن ماسات BIGO",
    tags: ["فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف حساب BIGO (Big ID)",
    packs: [
      { id: "bg1200",  name: "1200 ماسة",  sub: "حزمة البداية",  price: 950,   bonus: null },
      { id: "bg6000",  name: "6000 ماسة",  sub: "+ مكافأة",      price: 4500,  bonus: "بونص" },
      { id: "bg18000", name: "18000 ماسة", sub: "باقة المشاهير", price: 13000, bonus: "بونص" },
    ],
  },
  {
    id: "likee",
    name: "Likee",
    alias: "لايكي لايك",
    emoji: "✨",
    sub: "شحن ماسات Likee",
    tags: ["جديد"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف حساب Likee (ID)",
    packs: [
      { id: "lk100",  name: "100 ماسة",  sub: "حزمة البداية", price: 320,  bonus: null },
      { id: "lk1000", name: "1000 ماسة", sub: "+ مكافأة",     price: 2900, bonus: "بونص" },
    ],
  },
  {
    id: "imo",
    name: "IMO Premium",
    alias: "ايمو ايمو دايموند",
    emoji: "💬",
    sub: "اشتراك IMO بريميوم",
    tags: ["تواصل"],
    verifyType: "playerid",
    verifyHint: "أدخل رقم/معرّف حساب IMO",
    packs: [
      { id: "imo1",  name: "شهر واحد",  sub: "بريميوم",     price: 650,  bonus: null },
      { id: "imo3",  name: "3 أشهر",    sub: "بريميوم",     price: 1800, bonus: "توفير" },
      { id: "imo12", name: "12 شهرًا",  sub: "بريميوم",     price: 6200, bonus: "أفضل قيمة" },
    ],
  },
  {
    id: "patreon",
    name: "Patreon",
    alias: "باتريون باتريون عضوية",
    emoji: "🎨",
    sub: "دعم أي مبدع على Patreon",
    tags: ["دعم المبدعين"],
    verifyType: "email",
    verifyHint: "أدخل بريد حساب Patreon لديك",
    packs: [
      { id: "pt5",  name: "اشتراك 5$/شهر",  sub: "لأي مبدع", price: 1100,  bonus: null },
      { id: "pt10", name: "اشتراك 10$/شهر", sub: "لأي مبدع", price: 2100,  bonus: null },
      { id: "pt25", name: "اشتراك 25$/شهر", sub: "لأي مبدع", price: 5000,  bonus: null },
    ],
  },
  {
    id: "giftapps",
    name: "شحن أي تطبيق آخر",
    alias: "بطاقات تطبيقات هدايا",
    emoji: "📲",
    sub: "بطاقات شرائية للتطبيقات",
    tags: ["حسب الطلب"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "ga10", name: "بطاقة 10$ (أي تطبيق)",  sub: "رمز فوري", price: 2350,  bonus: null },
      { id: "ga25", name: "بطاقة 25$ (أي تطبيق)",  sub: "رمز فوري", price: 5700,  bonus: null },
      { id: "ga50", name: "بطاقة 50$ (أي تطبيق)",  sub: "رمز فوري", price: 11200, bonus: null },
    ],
  },
];

/* ---------- بطاقات ومحافظ الدفع الإلكتروني (شحن رصيد بالدولار يوصل على البريد) ---------- */
const WALLETS = [
  {
    id: "paypal",
    name: "PayPal",
    alias: "باي بال بايبال بي بال pay pal باي بال شحن باي بال رصيد",
    emoji: "💙",
    sub: "شحن رصيد PayPal بالدولار",
    tags: ["الأكثر طلبًا", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريد حسابك في PayPal لنضيف الرصيد إليه",
    packs: [
      { id: "pp5",  name: "5 دولار",   sub: "رصيد فوري",     price: 1200,  bonus: null },
      { id: "pp10", name: "10 دولار",  sub: "رصيد فوري",     price: 2350,  bonus: null },
      { id: "pp25", name: "25 دولار",  sub: "أفضل قيمة",     price: 5700,  bonus: "توفير 175" },
      { id: "pp50", name: "50 دولار",  sub: "للمحترفين",     price: 11200, bonus: "توفير 550" },
    ],
  },
  {
    id: "payeer",
    name: "Payeer",
    alias: "بايير باير payeer شحن بايير رصيد بايير",
    emoji: "🟢",
    sub: "شحن محفظة Payeer بالدولار",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريد حسابك في Payeer لنضيف الرصيد إليه",
    packs: [
      { id: "py5",  name: "5 دولار",   sub: "رصيد فوري",   price: 1200,  bonus: null },
      { id: "py10", name: "10 دولار",  sub: "رصيد فوري",   price: 2350,  bonus: null },
      { id: "py25", name: "25 دولار",  sub: "أفضل قيمة",   price: 5700,  bonus: "توفير 175" },
    ],
  },
  {
    id: "skrill",
    name: "Skrill",
    alias: "سكرييل سكريل skrill moneybookers شحن سكريل",
    emoji: "💚",
    sub: "شحن محفظة Skrill بالدولار",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريد حسابك في Skrill لنضيف الرصيد إليه",
    packs: [
      { id: "sk10", name: "10 دولار",  sub: "رصيد فوري",   price: 2350,  bonus: null },
      { id: "sk25", name: "25 دولار",  sub: "أفضل قيمة",   price: 5700,  bonus: "توفير 175" },
      { id: "sk50", name: "50 دولار",  sub: "للمحترفين",   price: 11200, bonus: "توفير 550" },
    ],
  },
  {
    id: "wise",
    name: "Wise",
    alias: "وايز وايس wise transferwise تحويل وايز شحن وايز",
    emoji: "🕊️",
    sub: "شحن حساب Wise بالدولار",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريد حسابك في Wise لنضيف الرصيد إليه",
    packs: [
      { id: "ws10",  name: "10 دولار",   sub: "رصيد فوري",    price: 2350,  bonus: null },
      { id: "ws25",  name: "25 دولار",   sub: "أفضل قيمة",    price: 5700,  bonus: "توفير 175" },
      { id: "ws50",  name: "50 دولار",   sub: "للمحترفين",    price: 11200, bonus: "توفير 550" },
      { id: "ws100", name: "100 دولار",  sub: "أفضل قيمة",    price: 22000, bonus: "توفير 1500" },
    ],
  },
  {
    id: "redotpay",
    name: "RedotPay",
    alias: "ريدوت باي ريدوتباي redotpay بطاقة ريدوت فيزا ريدوت",
    emoji: "🔴",
    sub: "شحن بطاقة RedotPay الافتراضية",
    tags: ["الأكثر طلبًا", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريد حسابك في RedotPay لنضيف الرصيد إليه",
    packs: [
      { id: "rp10",  name: "10 دولار",   sub: "رصيد فوري",    price: 2350,  bonus: null },
      { id: "rp25",  name: "25 دولار",   sub: "أفضل قيمة",    price: 5700,  bonus: "توفير 175" },
      { id: "rp50",  name: "50 دولار",   sub: "للمحترفين",    price: 11200, bonus: "توفير 550" },
      { id: "rp100", name: "100 دولار",  sub: "أفضل قيمة",    price: 22000, bonus: "توفير 1500" },
    ],
  },
  {
    id: "neteller",
    name: "Neteller",
    alias: "نتيلر نتتلر neteller شحن نتيلر رصيد نتيلر",
    emoji: "🟡",
    sub: "شحن محفظة Neteller بالدولار",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريد حسابك في Neteller لنضيف الرصيد إليه",
    packs: [
      { id: "nt10", name: "10 دولار",  sub: "رصيد فوري",   price: 2350,  bonus: null },
      { id: "nt25", name: "25 دولار",  sub: "أفضل قيمة",   price: 5700,  bonus: "توفير 175" },
    ],
  },
  {
    id: "airtm",
    name: "Airtm",
    alias: "ايرتم إيرتم airtm شحن ايرتم رصيد ايرتم",
    emoji: "💠",
    sub: "شحن محفظة Airtm بالدولار",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريد حسابك في Airtm لنضيف الرصيد إليه",
    packs: [
      { id: "am10", name: "10 دولار",  sub: "رصيد فوري",   price: 2350,  bonus: null },
      { id: "am25", name: "25 دولار",  sub: "أفضل قيمة",   price: 5700,  bonus: "توفير 175" },
      { id: "am50", name: "50 دولار",  sub: "للمحترفين",   price: 11200, bonus: "توفير 550" },
    ],
  },
  {
    id: "visavirtual",
    name: "VISA افتراضية",
    alias: "فيزا افتراضية فيزا افتراضيه بطاقة فيزا فيزا فيرتوال فيزا مسبقة الدفع virtual visa",
    emoji: "💳",
    sub: "بطاقة VISA افتراضية مسبقة الدفع بالدولار",
    tags: ["فوري", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لاستلام بيانات البطاقة (الرقم والـCVV والتاريخ)",
    packs: [
      { id: "vs5",   name: "بطاقة 5 دولار",   sub: "رقم + CVV فوري",   price: 1250,  bonus: null },
      { id: "vs10",  name: "بطاقة 10 دولار",  sub: "رقم + CVV فوري",   price: 2400,  bonus: null },
      { id: "vs25",  name: "بطاقة 25 دولار",  sub: "أفضل قيمة",        price: 5750,  bonus: "توفير 125" },
      { id: "vs50",  name: "بطاقة 50 دولار",  sub: "للمحترفين",        price: 11300, bonus: "توفير 450" },
    ],
  },
];

/* توليد اسم لاعب وهمي واقعي حسب نوع التحقق (محاكاة) */
const FAKE_NAMES = [
  "HamzaLegend", "YacineDZ", "Sniper_Algerie", "MoGamer99",
  "KarimPro", "AnisKing", "RiadFn", "BilalOP", "ZakiYTB",
];

/* الأسئلة الشائعة */
const FAQS = [
  {
    q: "كم يستغرق وصول الشحنة بعد الدفع؟",
    a: "للألعاب: من 30 ثانية إلى 5 دقائق كحد أقصى، تصل مباشرة إلى حسابك داخل اللعبة (UC، جواهرات، ماس...) دون الحاجة لأي كلمة سر. للبطاقات والاشتراكات (نتفلكس، شاهد، Spotify، يوتيوب...): خلال 30 دقيقة كحد أقصى تصلك التفاصيل أو الرمز على بريدك الإلكتروني.",
  },
  {
    q: "كيف يعمل شحن بطاقات الدفع الإلكتروني (PayPal وPayeer وSkrill…)؟",
    a: "تختار المحفظة من قسم «💳 بطاقات دفع» في المتجر، تدخل بريد حسابك فيها، وتحدد المبلغ بالدولار (5$ إلى 100$). تدفع بالدينار الجزائري عبر SlickPay كأي طلب آخر، ونضيف الرصيد إلى حسابك في المحفظة خلال 30 دقيقة كحد أقصى. الأسعار محسوبة بسعر صرف اليوم مع هامش خدمة رمزي — لا رسوم خفية. لبطاقة VISA الافتراضية تصلك بيانات البطاقة كاملة (الرقم، تاريخ الانتهاء، CVV) على بريدك.",
  },
  {
    q: "ما طرق الدفع المتوفرة؟",
    a: "الدفع عبر SlickPay ببطاقة CIB / الذهبية (صفحة الدفع الرسمية SATIM). المبلغ يدفع مرة واحدة، ثم يقسم تلقائياً: هامش المتجر يصل حسابنا وتكلفة الشحن تصل للمورد مباشرة — لهذا لا نطلب منك أي دفع مسبق أو محفظة.",
  },
  {
    q: "هل تحتاجون كلمة سر حسابي في اللعبة؟",
    a: "أبداً. الشحن يتم عبر معرّف اللاعب (Player ID) أو اسم المستخدم فقط — وهي معلومات عامة في اللعبة. لا نطلب كلمة سر ولا رمز تحقق أبداً، وأي رسالة تطلبها باسمنا فهي نصب.",
  },
  {
    q: "شحنت ولم يصل الكريدي، ماذا أفعل؟",
    a: "نادراً جداً أن يحدث هذا لأسباب تقنية من مزود اللعبة. افتح صفحة التتبع وأدخل رقم طلبك: إن ظهرت حالة «مُسلَّم» والكريدي غير ظاهر فأعد تشغيل اللعبة (تأخر الظهور وارد). إن ظهرت «قيد المعالجة» أكثر من 10 دقائق راسلنا واتساب فوراً برقم الطلب. للبطاقات: إن لم تصلك الرسالة على بريدك خلال 30 دقيقة تواصل معنا.",
  },
  {
    q: "كيف أثبّت التطبيق على هاتفي؟",
    a: "من متصفح الهاتف: أندرويد (Chrome) → اضغط «إضافة إلى الشاشة الرئيسية» من قائمة النقاط الثلاث. آيفون (Safari) → زر المشاركة → «إضافة إلى الشاشة الرئيسية». يثبت المتجر كتطبيق مستقل يعمل حتى بدون إنترنت للصفحات المحفوظة.",
  },
  {
    q: "هل الأسعار نهائية؟",
    a: "الأسعار المعروضة نهائية شاملة كل الرسوم. ما تراه في صفحة الدفع هو بالضبط ما يخصم من بطاقتك — لا عمولة خفية ولا رسوم إضافية عند التسليم.",
  },
];
