/* ============================================================
   شحنك DZ — data.js
   بيانات الألعاب والبطاقات والاشتراكات والأسئلة الشائعة
   الأسعار نموذجية — عدّلها حسب أسعار موردك الحقيقية
   ============================================================ */

/* ---------- الألعاب (شحن مباشر على معرف اللاعب) ---------- */
const GAMES = [
  {
    id: "pubg",
    name: "PUBG Mobile",
    emoji: "🎯",
    sub: "شحن UC فوري",
    tags: ["الأكثر مبيعاً", "فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (Player ID) — تجده أسفل صورك الشخصية في اللعبة",
    packs: [
      { id: "uc60",   name: "60 UC",    sub: "باقة البداية",   price: 220,   bonus: null },
      { id: "uc325",  name: "325 UC",   sub: "+ مكافأة 25",    price: 950,   bonus: "بونص 25" },
      { id: "uc660",  name: "660 UC",   sub: "+ مكافأة 60",    price: 1800,  bonus: "بونص 60" },
      { id: "uc1800", name: "1800 UC",  sub: "+ مكافأة 180",   price: 4700,  bonus: "بونص 180" },
      { id: "uc3850", name: "3850 UC",  sub: "+ مكافأة 450",   price: 9500,  bonus: "بونص 450" },
      { id: "uc8100", name: "8100 UC",  sub: "باقة الملوك",    price: 19000, bonus: "بونص 1200" },
    ],
  },
  {
    id: "freefire",
    name: "Free Fire",
    emoji: "🔥",
    sub: "جواهرات في ثوانٍ",
    tags: ["فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (ID) من صفحة الحساب في اللعبة",
    packs: [
      { id: "ff100",  name: "100 جوهرة",   sub: "باقة البداية",  price: 190,  bonus: null },
      { id: "ff310",  name: "310 جوهرة",   sub: "+ مكافأة 31",   price: 550,  bonus: "بونص 31" },
      { id: "ff520",  name: "520 جوهرة",   sub: "+ مكافأة 52",   price: 900,  bonus: "بونص 52" },
      { id: "ff1060", name: "1060 جوهرة",  sub: "+ مكافأة 106",  price: 1750, bonus: "بونص 106" },
      { id: "ff2180", name: "2180 جوهرة",  sub: "باقة المنافسة", price: 3500, bonus: "بونص 218" },
    ],
  },
  {
    id: "mobilelegends",
    name: "Mobile Legends",
    emoji: "⚔️",
    sub: "ماس ورموز سحرية",
    tags: ["جديد"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب ورقم المنطقة (Zone ID)",
    packs: [
      { id: "ml86",   name: "86 ماس",    sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "ml172",  name: "172 ماس",   sub: "+ مكافأة",      price: 470,  bonus: "بونص" },
      { id: "ml257",  name: "257 ماس",   sub: "+ مكافأة",      price: 700,  bonus: "بونص" },
      { id: "ml706",  name: "706 ماس",   sub: "باقة المتابعة", price: 1900, bonus: "بونص" },
      { id: "ml2195", name: "2195 ماس",  sub: "باقة الملوك",   price: 5600, bonus: "بونص" },
    ],
  },
  {
    id: "roblox",
    name: "Roblox",
    emoji: "🧱",
    sub: "روبوكس للحساب مباشرة",
    tags: ["الأكثر طلباً"],
    verifyType: "username",
    verifyHint: "أدخل اسم المستخدم (Username) الظاهر في حسابك",
    packs: [
      { id: "rbx80",   name: "80 روبوكس",   sub: "باقة البداية",  price: 260,   bonus: null },
      { id: "rbx400",  name: "400 روبوكس",  sub: "باقة البناء",   price: 1200,  bonus: null },
      { id: "rbx800",  name: "800 روبوكس",  sub: "باقة المبدعين", price: 2350,  bonus: null },
      { id: "rbx1700", name: "1700 روبوكس", sub: "باقة الاحتراف", price: 4800,  bonus: null },
      { id: "rbx4500", name: "4500 روبوكس", sub: "باقة الملوك",   price: 12500, bonus: null },
    ],
  },
  {
    id: "valorant",
    name: "Valorant",
    emoji: "🎮",
    sub: "نقاط VP لسلاحك المفضل",
    tags: ["شحن مباشر"],
    verifyType: "username",
    verifyHint: "أدخل اسم حساب Riot بصيغة name#tag — مثال: SniperDZ#EUW",
    packs: [
      { id: "vp1000", name: "1000 VP", sub: "باقة البداية",  price: 1350, bonus: null },
      { id: "vp2050", name: "2050 VP", sub: "+ مكافأة 250",  price: 2600, bonus: "بونص 250" },
      { id: "vp3650", name: "3650 VP", sub: "+ مكافأة 350",  price: 4600, bonus: "بونص 350" },
      { id: "vp5350", name: "5350 VP", sub: "باقة الاحتراف", price: 6700, bonus: null },
    ],
  },
  {
    id: "codm",
    name: "Call of Duty Mobile",
    emoji: "🎖️",
    sub: "نقاط CP بالمعرّف مباشرة",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (UID) من إعدادات اللعبة ← معلومات الحساب",
    packs: [
      { id: "cp80",   name: "80 CP",    sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "cp420",  name: "420 CP",   sub: "+ مكافأة",      price: 1150, bonus: "بونص" },
      { id: "cp880",  name: "880 CP",   sub: "+ مكافأة",      price: 2300, bonus: "بونص" },
      { id: "cp2400", name: "2400 CP",  sub: "باقة الاحتراف", price: 6100, bonus: "بونص" },
    ],
  },
  {
    id: "genshin",
    name: "Genshin Impact",
    emoji: "🌠",
    sub: "بلورات جينيسِس + بركة القمر",
    tags: ["فوري"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف HoYoverse (UID — 9 أرقام)",
    packs: [
      { id: "gs60",   name: "60 بلورة",     sub: "باقة البداية",         price: 260,   bonus: null },
      { id: "gs330",  name: "330 بلورة",    sub: "+ مكافأة 30",          price: 1300,  bonus: "بونص 30" },
      { id: "gs1090", name: "1090 بلورة",   sub: "+ مكافأة 90",          price: 4200,  bonus: "بونص 90" },
      { id: "gs2240", name: "2240 بلورة",   sub: "+ مكافأة 240",         price: 8400,  bonus: "بونص 240" },
      { id: "gs3880", name: "3880 بلورة",   sub: "باقة الملوك",          price: 14000, bonus: "بونص 600" },
      { id: "welkin", name: "بركة القمر",   sub: "اشتراك 30 يوماً يومياً", price: 900,  bonus: null },
    ],
  },
  {
    id: "clashofclans",
    name: "Clash of Clans",
    emoji: "🏰",
    sub: "جواهر لقريتك",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل وسم اللاعب (Player Tag) — يبدأ بـ # مثل #2ABC123",
    packs: [
      { id: "coc80",   name: "80 جوهرة",    sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "coc500",  name: "500 جوهرة",   sub: "+ مكافأة 65",   price: 1400, bonus: "بونص 65" },
      { id: "coc1200", name: "1200 جوهرة",  sub: "+ مكافأة 150",  price: 3300, bonus: "بونص 150" },
      { id: "coc2500", name: "2500 جوهرة",  sub: "باقة الاحتراف", price: 6500, bonus: "بونص 350" },
    ],
  },
  {
    id: "clashroyale",
    name: "Clash Royale",
    emoji: "👑",
    sub: "جواهر لكرسيك الملكي",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل وسم اللاعب (Player Tag) — يبدأ بـ # مثل #2ABC123",
    packs: [
      { id: "cr80",   name: "80 جوهرة",    sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "cr500",  name: "500 جوهرة",   sub: "+ مكافأة",      price: 1400, bonus: "بونص" },
      { id: "cr1200", name: "1200 جوهرة",  sub: "+ مكافأة",      price: 3300, bonus: "بونص" },
      { id: "cr2500", name: "2500 جوهرة",  sub: "باقة الاحتراف", price: 6500, bonus: "بونص" },
    ],
  },
  {
    id: "brawlstars",
    name: "Brawl Stars",
    emoji: "⭐",
    sub: "جواهر لبطلك المفضل",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل وسم اللاعب (Player Tag) — يبدأ بـ # مثل #2ABC123",
    packs: [
      { id: "brs30",  name: "30 جوهرة",   sub: "باقة البداية",  price: 180,  bonus: null },
      { id: "brs80",  name: "80 جوهرة",   sub: "+ مكافأة",      price: 460,  bonus: "بونص" },
      { id: "brs170", name: "170 جوهرة",  sub: "+ مكافأة",      price: 900,  bonus: "بونص" },
      { id: "brs360", name: "360 جوهرة",  sub: "باقة الاحتراف", price: 1850, bonus: "بونص" },
    ],
  },
  {
    id: "8ballpool",
    name: "8 Ball Pool",
    emoji: "🎱",
    sub: "عملات لطاولتك",
    tags: ["شحن مباشر"],
    verifyType: "playerid",
    verifyHint: "أدخل معرّف اللاعب (UID) من صفحة الحساب في اللعبة",
    packs: [
      { id: "8bp100",   name: "100 عملة",     sub: "باقة البداية",  price: 260,   bonus: null },
      { id: "8bp1000",  name: "1000 عملة",    sub: "+ مكافأة",      price: 2000,  bonus: "بونص" },
      { id: "8bp10000", name: "10 000 عملة",  sub: "باقة الاحتراف", price: 17000, bonus: "بونص" },
    ],
  },
  {
    id: "eafc",
    name: "EA FC موبايل",
    emoji: "⚽",
    sub: "نقاط FC لفريق أحلامك",
    tags: ["جديد"],
    verifyType: "username",
    verifyHint: "أدخل معرّف EA (EA ID) الخاص بحسابك",
    packs: [
      { id: "fcp100",  name: "100 نقطة FC",  sub: "باقة البداية",  price: 240,  bonus: null },
      { id: "fcp500",  name: "500 نقطة FC",  sub: "+ مكافأة",      price: 1150, bonus: "بونص" },
      { id: "fcp1200", name: "1200 نقطة FC", sub: "باقة الاحتراف", price: 2700, bonus: "بونص" },
    ],
  },
  {
    id: "fortnite",
    name: "Fortnite",
    emoji: "🛠️",
    sub: "V-Bucks للمعركة الملكية",
    tags: ["جديد"],
    verifyType: "username",
    verifyHint: "أدخل اسم حساب Epic Games",
    packs: [
      { id: "vb1000",  name: "1000 V-Bucks",  sub: "باقة المعركة",  price: 1700,  bonus: null },
      { id: "vb2800",  name: "2800 V-Bucks",  sub: "باقة التواقم",  price: 4600,  bonus: null },
      { id: "vb5000",  name: "5000 V-Bucks",  sub: "باقة الأساطير", price: 7900,  bonus: null },
      { id: "vb13500", name: "13500 V-Bucks", sub: "باقة الملوك",   price: 19000, bonus: null },
    ],
  },
  {
    id: "steam",
    name: "بطاقة Steam Wallet",
    emoji: "🕹️",
    sub: "رصيد متجر عالمي",
    tags: ["رمز يوصلك على البريد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "st10", name: "بطاقة 10$",  sub: "رمز رقمي فوري", price: 2200,  bonus: null },
      { id: "st20", name: "بطاقة 20$",  sub: "رمز رقمي فوري", price: 4300,  bonus: null },
      { id: "st50", name: "بطاقة 50$",  sub: "رمز رقمي فوري", price: 10500, bonus: null },
    ],
  },
];

/* ---------- بطاقات واشتراكات (تسليم على البريد) ---------- */
const CARDS = [
  {
    id: "netflix",
    name: "Netflix",
    emoji: "🎬",
    sub: "أفلام ومسلسلات بجودة 4K",
    tags: ["الأكثر طلباً", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "nf1", name: "شهر واحد", sub: "باقة البداية · جودة 4K", price: 1500, bonus: null },
      { id: "nf2", name: "شهرين",   sub: "جودة 4K · شاشتان",      price: 2800, bonus: "توفير 200" },
      { id: "nf3", name: "3 أشهر",  sub: "جودة 4K · شاشتان",      price: 4000, bonus: "توفير 500" },
    ],
  },
  {
    id: "shahid",
    name: "شاهد VIP",
    emoji: "📺",
    sub: "أفلام ومسلسلات عربية وأجنبية",
    tags: ["عربي", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال تفاصيل الاشتراك عليه",
    packs: [
      { id: "sh1",  name: "شهر واحد VIP",  sub: "باقة البداية",     price: 900,  bonus: null },
      { id: "sh3",  name: "3 أشهر VIP",    sub: "باقة العائلة",     price: 2500, bonus: "بونص" },
      { id: "sh12", name: "سنة كاملة VIP", sub: "أفضل قيمة",        price: 8500, bonus: "توفير كبير" },
    ],
  },
  {
    id: "spotify",
    name: "Spotify Premium",
    emoji: "🎵",
    sub: "موسيقى بلا إعلانات",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "sp1",  name: "شهر واحد", sub: "حساب فردي",   price: 900,  bonus: null },
      { id: "sp3",  name: "3 أشهر",   sub: "حساب فردي",   price: 2500, bonus: "توفير" },
      { id: "sp6",  name: "6 أشهر",   sub: "حساب فردي",   price: 4700, bonus: "توفير أكبر" },
      { id: "sp12", name: "12 شهراً", sub: "أفضل قيمة",   price: 8500, bonus: "أفضل قيمة" },
    ],
  },
  {
    id: "youtube",
    name: "YouTube Premium",
    emoji: "▶️",
    sub: "بلا إعلانات + يوتيوب موسيقى",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "yt1",  name: "شهر واحد",  sub: "حساب فردي", price: 950,  bonus: null },
      { id: "yt3",  name: "3 أشهر",    sub: "حساب فردي", price: 2700, bonus: "توفير" },
      { id: "yt12", name: "سنة كاملة", sub: "أفضل قيمة", price: 9900, bonus: "توفير كبير" },
    ],
  },
  {
    id: "discord",
    name: "Discord Nitro",
    emoji: "🚀",
    sub: "إيموجي عالمي + بث HD",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز Nitro عليه",
    packs: [
      { id: "dn1", name: "شهر Nitro كامل", sub: "ترقية كاملة",     price: 1700, bonus: null },
      { id: "dn2", name: "14 يوم Boost",   sub: "تعبئة سيرفر",     price: 950,  bonus: null },
    ],
  },
  {
    id: "anghami",
    name: "أنغامي",
    emoji: "🎧",
    sub: "موسيقى عربية بلا إعلانات",
    tags: ["عربي", "خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "ang3",  name: "3 أشهر",   sub: "حساب فردي", price: 1600, bonus: null },
      { id: "ang12", name: "سنة كاملة", sub: "أفضل قيمة", price: 5200, bonus: "توفير" },
    ],
  },
  {
    id: "googleplay",
    name: "Google Play",
    emoji: "🤖",
    sub: "رصيد متجر أندرويد",
    tags: ["رمز يوصلك على البريد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "gp5",  name: "بطاقة 5$",  sub: "رمز رقمي فوري", price: 1150, bonus: null },
      { id: "gp10", name: "بطاقة 10$", sub: "رمز رقمي فوري", price: 2200, bonus: null },
      { id: "gp25", name: "بطاقة 25$", sub: "رمز رقمي فوري", price: 5400, bonus: null },
    ],
  },
  {
    id: "itunes",
    name: "iTunes / App Store",
    emoji: "🍎",
    sub: "رصيد متجر آبل",
    tags: ["رمز يوصلك على البريد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "it5",  name: "بطاقة 5$",  sub: "رمز رقمي فوري", price: 1150,  bonus: null },
      { id: "it10", name: "بطاقة 10$", sub: "رمز رقمي فوري", price: 2200,  bonus: null },
      { id: "it20", name: "بطاقة 20$", sub: "رمز رقمي فوري", price: 4300,  bonus: null },
      { id: "it50", name: "بطاقة 50$", sub: "رمز رقمي فوري", price: 10500, bonus: null },
    ],
  },
  {
    id: "razer",
    name: "Razer Gold",
    emoji: "🐍",
    sub: "رصيد ألعاب عالمي",
    tags: ["رمز يوصلك على البريد"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لإرسال رمز البطاقة عليه",
    packs: [
      { id: "rz5",   name: "بطاقة 5$",   sub: "رمز رقمي فوري", price: 1150,  bonus: null },
      { id: "rz10",  name: "بطاقة 10$",  sub: "رمز رقمي فوري", price: 2200,  bonus: null },
      { id: "rz20",  name: "بطاقة 20$",  sub: "رمز رقمي فوري", price: 4400,  bonus: null },
      { id: "rz50",  name: "بطاقة 50$",  sub: "رمز رقمي فوري", price: 11000, bonus: null },
      { id: "rz100", name: "بطاقة 100$", sub: "رمز رقمي فوري", price: 21500, bonus: null },
    ],
  },
  {
    id: "xbox",
    name: "Xbox Game Pass",
    emoji: "🕹️",
    sub: "مئات الألعاب شهرياً",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "xgp1", name: "شهر واحد",  sub: "Game Pass Ultimate", price: 4500,  bonus: null },
      { id: "xgp3", name: "3 أشهر",    sub: "Ultimate",          price: 12500, bonus: "توفير" },
    ],
  },
  {
    id: "psplus",
    name: "PlayStation Plus",
    emoji: "🎮",
    sub: "ألعاب PS5 و PS4 شهرياً",
    tags: ["خلال 30 دقيقة"],
    verifyType: "email",
    verifyHint: "أدخل بريدك لتفعيل الاشتراك عليه",
    packs: [
      { id: "psp1",  name: "شهر واحد",  sub: "Essential", price: 3400,  bonus: null },
      { id: "psp3",  name: "3 أشهر",    sub: "Essential", price: 9500,  bonus: "توفير" },
      { id: "psp12", name: "12 شهراً",  sub: "Essential", price: 30000, bonus: "أفضل قيمة" },
    ],
  },
];

/* توليد اسم لاعب وهمي واقعي حسب نوع التحقق (محاكاة) */
const FAKE_NAMES = [
  "HamzaLegend", "YacineDZ", "Sniper_Algerie", "MoGamer99",
  "KarimPro", "AnisKing", "RiadFn", "BilalOP", "ZakiYTB",
];

/* الأسئلة الشائعة */
const FAQS = [
  {
    q: "كم يستغرق وصول الشحنة بعد الدفع؟",
    a: "للألعاب: من 30 ثانية إلى 5 دقائق كحد أقصى، تصل مباشرة إلى حسابك داخل اللعبة (UC، جواهرات، ماس...) دون الحاجة لأي كلمة سر. للبطاقات والاشتراكات (نتفلكس، شاهد، Spotify، يوتيوب...): خلال 30 دقيقة كحد أقصى تصلك التفاصيل أو الرمز على بريدك الإلكتروني.",
  },
  {
    q: "ما طرق الدفع المتوفرة؟",
    a: "الدفع عبر SlickPay ببطاقة CIB / الذهبية (صفحة الدفع الرسمية SATIM). المبلغ يدفع مرة واحدة، ثم يقسم تلقائياً: هامش المتجر يصل حسابنا وتكلفة الشحن تصل للمورد مباشرة — لهذا لا نطلب منك أي دفع مسبق أو محفظة.",
  },
  {
    q: "هل تحتاجون كلمة سر حسابي في اللعبة؟",
    a: "أبداً. الشحن يتم عبر معرّف اللاعب (Player ID) أو اسم المستخدم فقط — وهي معلومات عامة في اللعبة. لا نطلب كلمة سر ولا رمز تحقق أبداً، وأي رسالة تطلبها باسمنا فهي نصب.",
  },
  {
    q: "شحنت ولم يصل الكريدي، ماذا أفعل؟",
    a: "نادراً جداً أن يحدث هذا لأسباب تقنية من مزود اللعبة. افتح صفحة التتبع وأدخل رقم طلبك: إن ظهرت حالة «مُسلَّم» والكريدي غير ظاهر فأعد تشغيل اللعبة (تأخر الظهور وارد). إن ظهرت «قيد المعالجة» أكثر من 10 دقائق راسلنا واتساب فوراً برقم الطلب. للبطاقات: إن لم تصلك الرسالة على بريدك خلال 30 دقيقة تواصل معنا.",
  },
  {
    q: "كيف أثبّت التطبيق على هاتفي؟",
    a: "من متصفح الهاتف: أندرويد (Chrome) → اضغط «إضافة إلى الشاشة الرئيسية» من قائمة النقاط الثلاث. آيفون (Safari) → زر المشاركة → «إضافة إلى الشاشة الرئيسية». يثبت المتجر كتطبيق مستقل يعمل حتى بدون إنترنت للصفحات المحفوظة.",
  },
  {
    q: "هل الأسعار نهائية؟",
    a: "الأسعار المعروضة نهائية شاملة كل الرسوم. ما تراه في صفحة الدفع هو بالضبط ما يخصم من بطاقتك — لا عمولة خفية ولا رسوم إضافية عند التسليم.",
  },
];
